spring:
  application:
    name: ${APPLICATION_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-service
          uri: lb://DEMO-SERVICE
          predicates: 
            - Path=/ping
server:
  port: ${INTERNAL_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}