spring:
  application:
    name: ${APPLICATION_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: demo-service
          uri: http://DEMO-SERVICE
          predicates: 
            - Path=/ping
        - id: authentication
          uri: http://SSO-SERVICE-TEST
          predicates: 
            - Path=/auth/login, /auth/logout, /auth/valid-token
        - id: authorization
          uri: http://SSO-SERVICE-TEST
          predicates:
            - Path=/users/**
          filters:
          - name: AuthorizationFilter
        - id: user-front
          uri: http://USER-FRONT
          predicates:
            - Path=/assets/**
server:
  port: ${INTERNAL_PORT}