spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: lb://DEMO
          predicates: 
            - Path=/ping
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#log
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            level: trace
            route:
              RouteDefinitionRouteLocator: info